### ISSUE TITLE
Store received frames

### ISSUE THREAD

**Issue by Kamal-Sonani** [jspiva/LedPixelController#1]
Is it possible to store frames which received in e1.31 or dmx?

For after playback?(without real time data stream)

**Comment by jspiva** [comment]
The design is to stream them directly to the outputs, in as close to real-time as possible.  This is done for the ability to perform a light show across multiple devices running this software, from a single e1.31 source.
It is definitely possible to pre-define a show and store/play it from the EEPROM, but that is not the purpose of this project.  You are more than welcome to fork this project and utilize the code that writes to the pixel strings and build your own code to read/write from the EEPROM.

**Comment by jspiva** [comment]
I'm closing this as it is a question/enhancement that it not directly in line with this project's design/purpose.
