### ISSUE TITLE
LedPixelController:61:42: error: 'D0' was not declared in this scope

### ISSUE THREAD

**Issue by jnagy197163** [jspiva/LedPixelController#3]
const uint8_t PINS[CHANNEL_COUNT] = {D0, D1, D2, D3, D5, D6, D7, D8};

I know I'm doing something wrong  , And unable to figure it out, Could you please explain what I am doing wrong 
Thank You

**Comment by jspiva** [comment]
Based on the variant of the esp8266 board you have selected there may or may not be individual ports defined. You should check the pinout of the model you are using to determine the best setup.

Below is a link to the eps8266 variants, each should have a "pins_arduino.h" file that defines the pin constants. You should be able to see what pins your board has available, and adjust the code before you load it into your board.
https://github.com/esp8266/Arduino/tree/master/variants

**Comment by jspiva** [comment]
I'm closing this issue, as it appears from your other comment that you were successful in remedying the issue by adjusting your board selection.

Thanks @jnagy197163 for the response...
https://github.com/jspiva/LedPixelController/commit/ddc2788ac9863bce6d611309799797c203f9e796
