### ISSUE TITLE
Weird random pixels turning on randomly.

### ISSUE THREAD

**Issue by SuperBluw** [jspiva/LedPixelController#4]
Hi, not sure if anyone has experienced this issue, but random pixels of mine are turning off and on when playing through a vixen sequence, I'm running around 150 pixels per universe and 4 universes total, not sure if anyone else has had this issue, it happens on my nodeMCU and my Wemos D1. Any help is appreciated.

**Comment by jspiva** [comment]
Have you included a pull-down resistor in your circuit?  Check out this circuit diagram...
[https://www.hackster.io/jasonspiva/esp8266-e1-31-multiplexing-pixel-controller-002072](url)
The outputs of SN74 buffer will float when not enabled, which can cause strange things to occur with the lights.  The resistor holds the output at zero when the channel is not currently being sent data.

**Comment by SuperBluw** [comment]
Yep, that was exactly it, thank you sir for helping me out!
